---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8282}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[aws]
      - recipe[jdr-jamwiki::default]
    attributes:
